use crate::pixel::*;
use crate::edgeplan::*;
use super::scanline_shard_intercept::*;

use std::ops::{Range};

///
/// A shard subpixel represents a vertical subpixel generated by combining several shards
///
/// These are used when a region of a shape requires more vertical detail than is available by sampling along a
/// a single pixel line. In this case, we sample several subpixels and merge them together to generate a single
/// pixel shard to render.
///
/// Places where subpixels are required are determined by querying the `EdgeDescriptor::apexes()` (they're regions
/// where the curve changes direction over the course of a single pixel)
///
pub struct ShardSubPixel {
    shape_id:           ShapeId,
    shape_descriptor:   ShapeDescriptor,
    blend:              InterceptBlend,
    opacity:            f32,
}

impl<'a, 'b> From<&'a ScanlineShardIntercept<'b>> for ShardSubPixel {
    #[inline]
    fn from(intercept: &'a ScanlineShardIntercept<'b>) -> Self {
        ShardSubPixel {
            shape_id:           intercept.shape_id(),
            blend:              intercept.blend().clone(),
            opacity:            intercept.opacity(),
            shape_descriptor:   intercept.shape_descriptor().clone(),
        }
    }
}

impl ShardSubPixel {
    ///
    /// Retrieves the shape ID for this subpixel
    ///
    #[inline]
    pub fn shape_id(&self) -> ShapeId {
        self.shape_id
    }

    ///
    /// Combines the effect of an intercept into this subpixel
    ///
    pub fn combine(&mut self, intercept: &ScanlineShardIntercept<'_>) {
        // TODO: for fade blends, we need to combine the fades (although the opacity is probably the most important thing to add up here)
        // (This will use the first blend ratio, which is pretty close, but will not look right for things like a gap in the middle, or where the
        // slope changes a lot over the subpixels)

        // Overall opacity of the current 
        self.opacity += intercept.opacity();
    }

    ///
    /// Adds the rendering of this subpixel into the program stack
    ///
    #[inline]
    pub fn render(&self, program_stack: &mut Vec<PixelProgramPlan>, x_range: &Range<f64>) {
        self.blend.render(program_stack, &self.shape_descriptor, self.opacity, x_range);
    }
}
