use super::intercept_blend::*;
use super::scanline_shard_intercept::*;

use crate::pixel::*;
use crate::edgeplan::*;

use std::ops::{Range};

///
/// A shard subpixel represents a vertical subpixel generated by combining several shards
///
/// These are used when a region of a shape requires more vertical detail than is available by sampling along a
/// a single pixel line. In this case, we sample several subpixels and merge them together to generate a single
/// pixel shard to render.
///
/// Places where subpixels are required are determined by querying the `EdgeDescriptor::apexes()` (they're regions
/// where the curve changes direction over the course of a single pixel)
///
#[derive(Debug)]
pub struct ShardSubPixel {
    shape_id:           ShapeId,
    shape_descriptor:   ShapeDescriptor,
    blends:             Vec<(f32, InterceptBlend)>,
}

impl<'a, 'b> From<&'a ScanlineShardIntercept<'b>> for ShardSubPixel {
    #[inline]
    fn from(intercept: &'a ScanlineShardIntercept<'b>) -> Self {
        let mut blends = Vec::with_capacity(8);
        blends.push((intercept.opacity(), intercept.blend().clone()));

        ShardSubPixel {
            shape_id:           intercept.shape_id(),
            blends:             blends,
            shape_descriptor:   intercept.shape_descriptor().clone(),
        }
    }
}

impl ShardSubPixel {
    ///
    /// Retrieves the shape ID for this subpixel
    ///
    #[inline]
    pub fn shape_id(&self) -> ShapeId {
        self.shape_id
    }

    ///
    /// Combines the effect of an intercept into this subpixel
    ///
    #[inline]
    pub fn combine(&mut self, intercept: &ScanlineShardIntercept<'_>) {
        self.blends.push((intercept.opacity(), intercept.blend().clone()));
    }

    ///
    /// True if this subpixel should be considered opaque
    ///
    #[inline]
    pub fn is_opaque(&self) -> bool {
        false

        /* -- or we can do this, which actually calculates opacity. This is rarely true though so probably not worth the effort.
        if self.shape_descriptor.is_opaque {
            let mut total_opacity = 0.0;

            for (opacity, blend) in self.blends.iter(){
                if let InterceptBlend::Solid = blend {
                    total_opacity += opacity
                } else {
                    return false;
                }
            }

            total_opacity >= 1.0
        } else {
            false
        }
        */
    }

    ///
    /// Adds the rendering of this subpixel into the program stack
    ///
    #[inline]
    pub fn render(&self, program_stack: &mut Vec<PixelProgramPlan>, x_range: &Range<f64>) {
        // Region that we're rendering in
        let x1 = x_range.start.floor();
        let x2 = x_range.end.ceil();

        // Calculate the alpha coverage at the start and end of the x range
        if x2 <= x1 + 1.0 {
            // Calculate the overall coverage of this pixel
            let mut alpha_coverage = 0.0;
            for (opacity, blend) in self.blends.iter() {
                alpha_coverage += blend.pixel_coverage(x1) as f32 * *opacity;
            }

            if alpha_coverage < 1.0 {
                program_stack.push(PixelProgramPlan::Merge(alpha_coverage));
            } else {
                // Filled pixel
                program_stack.extend(self.shape_descriptor.programs.iter().map(|program| PixelProgramPlan::Run(*program)));
                return;
            }
        } else {
            // Create a linear blend using the start and end pixels
            let x2 = x2-1.0;

            let mut start_coverage  = 0.0;
            let mut end_coverage    = 0.0;

            for (opacity, blend) in self.blends.iter() {
                start_coverage  += blend.pixel_coverage(x1) as f32 * *opacity;
                end_coverage    += blend.pixel_coverage(x2) as f32 * *opacity;
            }

            if start_coverage < 1.0 || end_coverage < 1.0 {
                program_stack.push(PixelProgramPlan::LinearMerge(start_coverage, end_coverage));
            } else {
                // Filled pixel
                program_stack.extend(self.shape_descriptor.programs.iter().map(|program| PixelProgramPlan::Run(*program)));
                return;
            }
        }

        // Run the programs and apply the blend
        program_stack.extend(self.shape_descriptor.programs.iter().map(|program| PixelProgramPlan::Run(*program)));
        program_stack.push(PixelProgramPlan::StartBlend);
    }
}
