use crate::pixel::*;
use crate::edgeplan::*;
use super::intercept_blend::*;
use super::scanline_shard_intercept::*;

use std::ops::{Range};

///
/// A shard subpixel represents a vertical subpixel generated by combining several shards
///
/// These are used when a region of a shape requires more vertical detail than is available by sampling along a
/// a single pixel line. In this case, we sample several subpixels and merge them together to generate a single
/// pixel shard to render.
///
/// Places where subpixels are required are determined by querying the `EdgeDescriptor::apexes()` (they're regions
/// where the curve changes direction over the course of a single pixel)
///
#[derive(Debug)]
pub struct ShardSubPixel {
    shape_id:           ShapeId,
    shape_descriptor:   ShapeDescriptor,
    blend:              InterceptBlend,
    opacity:            f64,
}

impl<'a, 'b> From<&'a ScanlineShardIntercept<'b>> for ShardSubPixel {
    #[inline]
    fn from(intercept: &'a ScanlineShardIntercept<'b>) -> Self {
        ShardSubPixel {
            shape_id:           intercept.shape_id(),
            blend:              intercept.blend().clone(),
            opacity:            intercept.opacity() as f64,
            shape_descriptor:   intercept.shape_descriptor().clone(),
        }
    }
}

impl ShardSubPixel {
    ///
    /// Retrieves the shape ID for this subpixel
    ///
    #[inline]
    pub fn shape_id(&self) -> ShapeId {
        self.shape_id
    }

    ///
    /// Combines the effect of an intercept into this subpixel
    ///
    pub fn combine(&mut self, intercept: &ScanlineShardIntercept<'_>) {
        // TODO: mixing f64 (from the blend) and f32 (from the intercept) here, want to make these consistent

        // Combine the blends
        let total_opacity       = self.opacity + (intercept.opacity() as f64);
        let our_opacity_ratio   = self.opacity/total_opacity;
        let their_opacity_ratio = 1.0 - our_opacity_ratio;

        let new_blend = match (&self.blend, intercept.blend()) {
            (InterceptBlend::Solid, InterceptBlend::Solid) => InterceptBlend::Solid,
            (_, _) => {
                self.blend.multiply_fade(our_opacity_ratio).nest(intercept.blend().multiply_fade(their_opacity_ratio))
            },
        };

        // Overall opacity of the current shard is increased by the newly added shard
        self.blend   = new_blend;
        self.opacity = (self.opacity + intercept.opacity() as f64).min(1.0);
    }

    ///
    /// True if this subpixel should be considered opaque
    ///
    #[inline]
    pub fn is_opaque(&self) -> bool {
        if self.opacity >= 1.0 && self.shape_descriptor.is_opaque {
            match self.blend {
                InterceptBlend::Solid   => true,
                _                       => false
            }
        } else {
            false
        }
    }

    ///
    /// Adds the rendering of this subpixel into the program stack
    ///
    #[inline]
    pub fn render(&self, program_stack: &mut Vec<PixelProgramPlan>, x_range: &Range<f64>) {
        self.blend.render(program_stack, &self.shape_descriptor, self.opacity as f32, x_range);
    }
}

///
/// Multiplies any blends in a stack with a given alpha value (or creates blends for empty stacks)
///
/// Makes the assumption that we're using a stack that's the output of InterceptBlend::render()
///
fn multiply_program_stack_alpha(stack: &mut Vec<PixelProgramPlan>, alpha: f64) {
    let alpha = alpha as f32;

    if let PixelProgramPlan::StartBlend = &stack[0] {
        // Adjust the existing blends (presuming just LinearMerge and Merge are present, and we're not very nested)
        stack.iter_mut().for_each(|plan| match plan {
            PixelProgramPlan::LinearMerge(start, finish)    => { *start *= alpha; *finish *= alpha; }
            PixelProgramPlan::Merge(val)                    => { *val *= alpha; }
            _                                               => { }
        })
    } else {
        // Create a new blend
        stack.insert(0, PixelProgramPlan::StartBlend);
        stack.push(PixelProgramPlan::Merge(alpha));
    }
}

///
/// Adds a pixel stack to another stack, assume both are the output of multiply_program_stack_alpha (so everything lines up)
///
fn add_stack_alphas(program_stack: &mut Vec<PixelProgramPlan>, add_stack: &Vec<PixelProgramPlan>) {
    use PixelProgramPlan::*;

    program_stack.iter_mut().zip(add_stack.iter())
        .for_each(|(mut stack, add)| match (&mut stack, add) {
            (LinearMerge(start, finish), LinearMerge(add_start, add_finish))    => { *start = (*start + *add_start).min(1.0); *finish = (*finish + *add_finish).min(1.0); },
            (Merge(alpha), Merge(add_alpha))                                    => { *alpha = (*alpha + *add_alpha).min(1.0); }
            (LinearMerge(start, finish), Merge(add_alpha))                      => { *start = (*start + *add_alpha).min(1.0); *finish = (*finish + *add_alpha).min(1.0); },
            (Merge(alpha), LinearMerge(add_start, add_finish))                  => { let alpha = *alpha; *stack = LinearMerge((alpha + add_start).min(1.0), (alpha + add_finish).min(1.0)); }
            _                                                                   => { }
        })
}
