use futures::stream::FuturesUnordered;
use wayland_client::{Proxy, Dispatch};

///
/// Structure used to dispatch futures from events generated by a wayland event queue
///
pub struct FloWaylandDispatcher {
    /// Actions that are pending 
    pending: Vec<Box<dyn Send + FnOnce(&SceneContext) -> BoxFuture<'static, ()>>>,
}

impl FloWaylandDispatcher {
    ///
    /// Creates a new dispatcher
    ///
    pub fn new() -> Self {
        FloWaylandDispatcher {
            pending: vec![]
        }
    }

    ///
    /// Dispatches an action to run in the scene
    ///
    pub fn dispatch<TFuture>(&mut self, action: impl 'static + Send + FnOnce(SceneContext) -> TFuture)
    where
        TFuture: 'static + Send + Future<Output=()>,
    {
        self.pending.push(Box::new(move |context| {
            action(context).boxed()
        }));
    }

    ///
    /// Runs the pending actions in a dispatcher
    ///
    pub fn execute_pending<'a, 'b>(dispatcher: &'a mut Self, context: &SceneContext) -> impl 'b + Future<Output=()> {
        // Drain the pending futures and put them in a futures-unordered
        let pending = dispatcher.pending
            .drain(..)
            .map(|pending_fn| pending_fn(context.clone()))
            .collect::<FuturesUnordered<_>>();

        // Result runs all the futures we've collected
        async move {
            while let Some(_) = pending.next().await { }
        }
    }
}
