use crate::pixel_program_cache::*;

use smallvec::*;

///
/// A shape descriptor provides information on the pixel programs to run inside of a shape
///
#[derive(Clone, Debug)]
pub struct ShapeDescriptor {
    /// The identifiers of the pixel programs to run when rendering this shape. These should be in reverse order (ie, the last one in this list will be run first)
    pub programs: SmallVec<[PixelProgramDataId; 1]>,

    /// Set to true if the shape is transparent (programs should be provided with the results generated by )
    pub is_transparent: bool,

    /// Shapes with a higher z-index are drawn first where they overlap with other shapes
    pub z_index: i64,
}
